### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by lili05020502**
李昱霆
http://52.25.153.68:3000/
http://52.25.153.68:3000/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
There should have some spacing between circles of image slider.

**Review by cwpeng — APPROVED** [review]
OK. Done.

Try to preload slider images for better user experience.

**Comment by lili05020502** [comment]
> OK. Done.
> 
> Try to preload slider images for better user experience.

Already add preload images function ，Please take a look ，thanks

**Review by cwpeng — APPROVED** [review]
Good. Better.

**Pull request merged**
